name: Readme CI
on:
  push:
    branches: [main]
  repository_dispatch:
    types: [readme]
  workflow_dispatch:
jobs:
  release:
    name: Update README
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Update notes summary
        uses: AnandChowdhary/notes-summary@master
        with:
          token: "${{ secrets.GH_PAT }}"
          directory: "notes"
